environments:
  dev:
  int:
  main:
  sprint:
  prod-blue:
  prod-green:

releases:
  - name: {{ requiredEnv "PROJECT" }}-{{ requiredEnv "BRANCH" | lower }}
    chart: ../helm/charts/eligibility-estimator
    values:
      - overrides/eligibility-estimator/eligibility-estimator.yaml.gotmpl
    labels:
      category: dts
      app: eligibility-estimator
      tier: frontend
    namespace: eligibility-estimator-{{ requiredEnv "BRANCH" | lower }}
    installed: true
