environments:
  dev:
  staging:
  dyna:
  main:
  prod:

releases:
  - name: {{ requiredEnv "PATH_PREFIX" }}-{{ requiredEnv "BRANCH" | lower }}
    chart: ../helm/charts/{{ requiredEnv "PROJECT" }}
    values:
      - overrides/{{ requiredEnv "PROJECT" }}/{{ requiredEnv "PROJECT" }}.yaml.gotmpl
    labels:
        category: dts
        app: {{ requiredEnv "PROJECT" }}
        tier: frontend
    namespace: {{ requiredEnv "PROJECT" }}
    installed: true
