environments:
  dev:
  int:
  main:
  sprint:
  prod-blue:
  prod-green:

releases:
  - name: {{ requiredEnv "PROJECT" }}-{{ requiredEnv "BRANCH" | lower }}
    chart: ../helm/charts/{{ requiredEnv "PROJECT" }}
    values:
      - overrides/{{ requiredEnv "PROJECT" }}/{{ requiredEnv "PROJECT" }}.yaml.gotmpl
    labels:
      category: dts
      app: {{ requiredEnv "PROJECT" }}
      tier: frontend
    namespace: {{ requiredEnv "PROJECT" }}-{{ requiredEnv "BRANCH" | lower }}
    installed: true
