environments:
  alpha:
  dev:
  staging:
  dyna:
  main:
  prod:

releases:
  - name: {{ requiredEnv "SUB_DOMAIN_PATH" }}
    chart: ../helm/charts/eligibility-estimator
    values:
      - overrides/eligibility-estimator/eligibility-estimator.yaml.gotmpl
    labels:
        category: dts
        app: {{ requiredEnv "PROJECT" }}
        tier: frontend
    namespace: {{ requiredEnv "PROJECT" }}
    installed: true
