version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    reviewers:
      - JeremyKennedy
      - KhalidAdan
    open-pull-requests-limit: 0
