checksumBehavior: ignore

nodeLinker: pnp

packageExtensions:
  chalk@5.4.1:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@4.3.0'
      '#supports-color': 'npm:supports-color@7.2.0'

  lint-staged@12.0.0:
    dependencies:
      chalk: 'npm:4.1.2'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.2.cjs
