nodeLinker: pnp # default: pnp
pnpMode: strict # default: strict

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

# Ideally this should be set to "throw" (Yarn's default).
# However, sometimes odd packages won't build properly on our infra, so we need to change to "ignore".
# Specifically, this is necessary when pulling the Design System direct from GitHub rather than NPM.
# In that case, we should temporarily set this to "ignore", and change back to "throw" when switching back to NPM.
checksumBehavior: ignore

# required workaround of Yarn PnP bug (https://github.com/chalk/chalk/issues/531)
packageExtensions:
  chalk@5.3.0:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2
