nodeLinker: node-modules # default: pnp
pnpMode: strict # default: strict

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

# Ideally this should be set to "throw" (Yarn's default).
# However, sometimes odd packages won't build properly on our infra, so we need to change to "ignore".
# Specifically, this is necessary when pulling the Design System direct from GitHub rather than NPM.
# In that case, we should temporarily set this to "ignore", and change back to "throw" when switching back to NPM.
checksumBehavior: ignore
