checksumBehavior: ignore

nodeLinker: pnp

packageExtensions:
  chalk@4.1.2:
    dependencies:
      ansi-styles: 'npm:4.3.0'
      supports-color: 'npm:7.2.0'
  ansi-styles@4.3.0: {} # Allows enforcing this version globally
  supports-color@7.2.0: {} # Allows enforcing this version globally

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.2.cjs
