pr:
- develop

variables:
  azureContainerRegistry.repository: 'eligibilityestimator'
  azureContainerRegistry.name: 'DTSShared-December/2023'
  azureContainerRegistry.domain: 'dtsshared.azurecr.io'
  tag: 'ADO-$(Build.BuildId)'
  APP_ENV: development
  NEXT_BUILD_DATE: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]
  LOGGING_LEVEL: "info"
  System.Debug: false

stages:
  - stage: Cache
    displayName: Pull latest image for caching
    jobs:
      - job:
        displayName: Pull latest image
        steps:

          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'login'

          - script: "docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true

  - stage: Build
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Container
        steps:

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'EsDBDMSEDDSub(400c5730-25f5-4ee6-a933-8b289b9ccb0d)'
              KeyVaultName: 'kv-oas-ee-dev'
              SecretsFilter: 'DEV-ADOBE-ANALYTICS-URL, NEXT-AUTH-PASSWORD, NEXT-AUTH-USERCODE'
              RunAsPreJob: false

          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'build'
              Dockerfile: './Dockerfile'
              tags: |
                $(tag)
                latest
                release-candidate
              arguments: |
                --pull
                --cache-from $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest
                --build-arg NEXT_BUILD_DATE=$(NEXT_BUILD_DATE)
                --build-arg ADOBE_ANALYTICS_URL=$(DEV-ADOBE-ANALYTICS-URL)
                --build-arg APP_ENV=$(APP_ENV)
                --build-arg LOGGING_LEVEL=$(LOGGING_LEVEL)

          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'push'
              tags: |
                $(tag)
                latest
                release-candidate
