trigger:
  - main

pr: none

variables:
  azureContainerRegistry.repository: 'eligibilityestimator'
  azureContainerRegistry.name: 'DTSShared-December/2023'
  azureContainerRegistry.domain: 'dtsshared.azurecr.io'
  tag: 'ADO-$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Container
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'login'
          - script: 'docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest'
            displayName: Pull latest for layer caching
            continueOnError: true
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'build'
              Dockerfile: './Dockerfile'
              tags: |
                $(tag)
                latest
                release-candidate
              arguments: |
                --pull 
                --cache-from $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest

          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'push'
              tags: |
                $(tag)
                latest
                release-candidate
