pr:
  - develop

variables:
  azureContainerRegistry.repository: 'eligibilityestimator'
  azureContainerRegistry.name: 'DTSShared-December/2023'
  azureContainerRegistry.domain: 'dtsshared.azurecr.io'
  app.environment: development
  app.buildDate: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]
  app.domain: 'https://app-eligibilityestimator-dev.azurewebsites.net/'
  app.logLevel: 'info'
  System.Debug: false

stages:
  - stage: Cache
    displayName: Pull latest image for caching
    jobs:
      - job:
        displayName: Pull latest image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'login'

          - script: 'docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest'
            displayName: Pull latest for layer caching
            continueOnError: true

  - stage: Build
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Container
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'id-eligibilityestimator-dev'
              KeyVaultName: 'kv-oas-ee-dev'
              SecretsFilter: 'DEV-ADOBE-ANALYTICS-URL, NEXT-AUTH-PASSWORD, NEXT-AUTH-USERCODE'
              RunAsPreJob: false

          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'build'
              Dockerfile: './Dockerfile'
              tags: |
                $(app.buildDate)
                latest
                release-candidate
              arguments: |
                --pull
                --cache-from $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest
                --build-arg HOME=/app
                --build-arg NEXT_BUILD_DATE=$(app.buildDate)
                --build-arg NEXTAUTH_URL=$(app.domain)
                --build-arg NEXT_AUTH_USERNAME=$(NEXT_AUTH_USERCODE)
                --build-arg NEXT_AUTH_PASSWORD=$(NEXT_AUTH_PASSWORD)
                --build-arg NEXTAUTH_SECRET=$(NEXT_AUTH_SECRET)
                --build-arg ADOBE_ANALYTICS_URL=$(DEV-ADOBE-ANALYTICS-URL)
                --build-arg APP_ENV=$(app.environment)
                --build-arg LOGGING_LEVEL=$(app.logLevel)

          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'push'
              tags: |
                $(app.buildDate)
                latest
                release-candidate
