trigger:
  - none

pr:
  - develop

pool:
  vmImage: ubuntu-latest

variables:
  azure.servicePrincipal: 'OASEE-Dynamic-Links-01/18/2024'
  webapp.name: 'app-eligibilityestimator-dev'
  webapp.resourceGroup: 'rg-eligibilityestimator-dev'
  webapp.slotName: null
  azureContainerRegistry.name: 'DTSShared-December/2023'
  azureContainerRegistry.repository: 'oas/eligibility-estimator'
  azureContainerRegistry.domain: 'dtsshared.azurecr.io'
  azureContainerRegistry.tag: 'preview-$(Build.SourceVersion)'
  app.environment: development
  app.buildDate: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]
  app.domain: null
  app.logLevel: 'info'
  System.Debug: false

steps:
  - task: PowerShell@2
    displayName: 'Decide which AppService slot to put this preview in'
    inputs:
      targetType: 'inline'
      script: |
        [int] $slotNumber = $(System.PullRequest.PullRequestId) % 4
        Write-Host "Generated slot number:"
        Write-Host "$slotNumber"
        Write-Host "From PRID"
        Write-Host "$(System.PullRequest.PullRequestId)"
        Write-Host "##vso[task.setvariable variable=webapp.slotName]$slotNumber"
        $deployURL = "https://app-eligibilityestimator-dev-pr-preview-$slotNumber.azurewebsites.net"
        Write-Host "##vso[task.setvariable variable=app.domain]$deployURL"

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'id-eligibilityestimator-dev'
      KeyVaultName: 'kv-oas-ee-dev'
      SecretsFilter: 'DEV-ADOBE-ANALYTICS-URL, NEXT-AUTH-PASSWORD, NEXT-AUTH-USERCODE'
      RunAsPreJob: false

  - task: Docker@2
    inputs:
      containerRegistry: '$(azureContainerRegistry.name)'
      repository: '$(azureContainerRegistry.repository)'
      command: 'login'
  - script: 'docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest'
    displayName: Pull latest for layer caching
    continueOnError: true

  - task: Docker@2
    displayName: 'Build image'
    inputs:
      containerRegistry: '$(azureContainerRegistry.name)'
      repository: '$(azureContainerRegistry.repository)'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(azureContainerRegistry.tag)
        latest
      arguments: |
        --cache-from $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest
        --build-arg home=/app
        --build-arg NEXT_BUILD_DATE=$(app.buildDate)
        --build-arg NEXTAUTH_URL=$(app.domain)
        --build-arg NEXT_AUTH_USERNAME=$(NEXT-AUTH-USERCODE)
        --build-arg NEXT_AUTH_PASSWORD=$(NEXT-AUTH-PASSWORD)
        --build-arg NEXTAUTH_SECRET=$(NEXT_AUTH_SECRET)
        --build-arg ADOBE_ANALYTICS_URL=$(DEV-ADOBE-ANALYTICS-URL)
        --build-arg APP_ENV=$(app.environment)
        --build-arg LOGGING_LEVEL=$(app.logLevel)

  - task: Docker@2
    displayName: 'Push image'
    inputs:
      containerRegistry: '$(azureContainerRegistry.name)'
      repository: '$(azureContainerRegistry.repository)'
      command: 'push'
      tags: |
        $(azureContainerRegistry.tag)
        latest

  - task: AzureCLI@2
    displayName: 'Create new slot in App Service'
    inputs:
      azureSubscription: $(azure.servicePrincipal)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp deployment slot create \
        --name $(webapp.name) \
        --resource-group $(webapp.resourceGroup) \
        --slot pr-preview-$(webapp.slotName) \
        --configuration-source $(webapp.name)
        # az webapp identity assign \
        # -g $(webapp.resourceGroup) \
        # -n $(webapp.name) \
        # --slot pr-preview-$(webapp.slotName) \
        # --identities /subscriptions/400c5730-25f5-4ee6-a933-8b289b9ccb0d/resourcegroups/rg-eligibilityestimator-dev/providers/microsoft.managedidentity/userassignedidentities/id-eligibilityestimator-dev

  - task: AzureCLI@2
    displayName: 'Deploy pr image to new slot'
    inputs:
      azureSubscription: $(azure.servicePrincipal)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp config container set \
        --docker-custom-image-name $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):$(azureContainerRegistry.tag) \
        --name $(webapp.name) \
        --slot pr-preview-$(webapp.slotName) \
        --resource-group $(webapp.resourceGroup)
