# This workflow will add a comment to the PR with the development or dynamic site

name: Comment environment in PR

on:
  pull_request:
    branches:
      - develop

jobs:
  comment_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2

        with:
          message: "Dynamic branch URL: https://app-eligibilityestimator-dev-pr-preview-${{github.event.pull_request.number}}.azurewebsites.net'"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
