name: Run scrapers
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_committer_name: DTS-STN
        git_committer_email: dts-stn+actions@github.com
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - run: corepack enable
    - run: yarn install
    # - run: git checkout -b legal-values-autoupdate
    - run: yarn run run-scraper
    - run: echo test > utils/api/scrapers/output/test.json
    # - uses: EndBug/add-and-commit@v9
    #   with:
    #     add: 'utils/api/scrapers/output/*.json'
    #     new_branch: legal-values-autoupdate
    #     committer_name: DTS-STN
    #     committer_email: dts-stn+actions@github.com
    # - run: |
    #       git add 'utils/api/scrapers/output/*.json'
    #       git commit -S -m "update legal values"
    # - run: git push -v --set-upstream origin legal-values-autoupdate
    - uses: peter-evans/create-pull-request@v4
      with:
        commit-message: auto-update legal values
        title: Auto-update legal values
        body: This is created by a bot, please review.
        branch: legal-values-autoupdate
        add-paths: |
          utils/api/scrapers/output/*.json
